version: '3'
services:
  web:
    build: client/
    ports:
      - "81:81"
    networks:
      - my_network
    container_name: web       

  app:
    build: tictactoe/
    networks:
      - my_network
    container_name: app

networks:
  my_network:
    driver: bridge