version: '3'
services:
  web:
    image: thehappyalien/tictactoe-web:latest
    ports:
      - "80:81"
    networks:
      - my_network
    container_name: web

  app:
    image: thehappyalien/tictactoe-app:latest
    networks:
      - my_network
    container_name: app

networks:
  my_network:
    driver: bridge